title: "M. V. Sivaselvan (Siva)"
author: "M. V. Sivaselvan"
description: "University at Buffalo"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false       # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "teaching.md", title: Teaching}
  - {file: "blog.md", title: Blog}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:mvs@buffalo.edu"}
  - {title: Github, icon: github, url: "https://github.com/mvsivaselvan"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/mvsivaselvan/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 
# Google analytics
google_analytics: G-7GJFSM8WV0

